resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/kencharos/flight-school
    branch: master

jobs:
- name: test-app
  plan:
  - get: flight-school
    trigger: true # gitリポジトリのpush を検知する。
  - task: tests
    file: flight-school/build.yml
  - task: run
    file: flight-school/run.yml
- name: test-run
  plan:
  - get: flight-school
    passed: [test-app] #test-appのあと
    trigger: true 
  - task: run2
    file: flight-school/run.yml

